config/routes.rb
Rails.application.routes.draw do
  get 'likes/create'
  get 'likes/delete'
  get 'likes/count'
  resources :arts
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "arts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/art.rb
class Art < ApplicationRecord
  has_and_belongs_to_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_and_belongs_to_many :arts

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/arts_controller.rb
class ArtsController < ApplicationController
  before_action :set_art, only: %i[ show edit update destroy ]

  # GET /arts or /arts.json
  def index
    @arts = Art.all
    #puts "*******************#{@arts}"
  end

  # GET /arts/1 or /arts/1.json
  def show
  end

  # GET /arts/new
  def new
    @art = Art.new
  end

  # GET /arts/1/edit
  def edit
  end

  # POST /arts or /arts.json
  def create
    @art = Art.new(art_params)

    respond_to do |format|
      if @art.save
        format.html { redirect_to art_url(@art), notice: "Art was successfully created." }
        format.json { render :show, status: :created, location: @art }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @art.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /arts/1 or /arts/1.json
  def update
    respond_to do |format|
      if @art.update(art_params)
        format.html { redirect_to art_url(@art), notice: "Art was successfully updated." }
        format.json { render :show, status: :ok, location: @art }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @art.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /arts/1 or /arts/1.json
  def destroy
    @art.destroy

    respond_to do |format|
      format.html { redirect_to arts_url, notice: "Art was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_art
      @art = Art.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def art_params
      params.require(:art).permit(:title, :description, :size)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    puts "Create ************"
    # current_user_id = User.find(current_user.id)
    @art = Art.find(params[:art_id])

    if current_user.arts.present?
      current_user.arts << @art
    else
      current_user.arts = [@art]
    end

    #puts current_user_id
    #puts @art

    redirect_to "/"
  end

  def delete
  end

  def count
    @like_count = Art.find(params[:art_id]).users.count
    puts "Count ********************* #{@like_count}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/arts_helper.rb
module ArtsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/arts/_art.html.erb
<div id="<%= dom_id art %>">
  <p>
    <strong>Title:</strong>
    <%= art.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= art.description %>
  </p>

  <p>
    <strong>Size:</strong>
    <%= art.size %>
  </p>

</div>

app/views/arts/_form.html.erb
<%= form_with(model: art) do |form| %>
  <% if art.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(art.errors.count, "error") %> prohibited this art from being saved:</h2>

      <ul>
        <% art.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :size, style: "display: block" %>
    <%= form.text_field :size %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/arts/edit.html.erb
<h1>Editing art</h1>

<%= render "form", art: @art %>

<br>

<div>
  <%= link_to "Show this art", @art %> |
  <%= link_to "Back to arts", arts_path %>
</div>

app/views/arts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Arts</h1>

<div id="arts">
  <% @arts.each do |art| %>
    <%= render art %>

    <% @total_likes = Art.find(art.id).users.count%>

    <p>
      <%= link_to "Show this art", art %>
      Likes <%= @total_likes%>
      ==================================================
    </p>
  <% end %>
</div>

<%= link_to "New art", new_art_path %>

</br></br></br>

app/views/arts/new.html.erb
<h1>New art</h1>

<%= render "form", art: @art %>

<br>

<div>
  <%= link_to "Back to arts", arts_path %>
</div>

app/views/arts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @art %>

<div>
  <%= link_to "Edit this art", edit_art_path(@art) %> |
  <%= link_to "Back to arts", arts_path %>
  <% if user_signed_in? %>
  | <%= link_to "Like", likes_create_path(:art_id => @art.id)%>
  <%end%>

  <%= button_to "Destroy this art", @art, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>


<html>
  <head>
    <title>ArtGallery</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </head>


<div class="container">
  <body >


      <div class="row justify-content-start">
        <div class="col-4">

        </div>
    </div>



<!--

       <p class="notice"><%#= notice %></p>
       <p class="alert"><%#= alert %></p>


-->

<% if user_signed_in? %>
Welcome
<%= current_user.email%>
<%= link_to "Sign out", destroy_user_session_path, data: { turbo_method: :delete } %>
<%else%>
<%= link_to "Sign In", user_session_path %>
<%end%>


   <div class="row justify-content-start">
     <div class="col-4">
       <%= yield %>

   </div>

   </br></br></br>
  </body>

</div>


  <div class="row justify-content-start">
    <div class="col-4">

    </div>
</div>
</div>
</html>

app/views/likes/count.html.erb
<h1>Likes#count</h1>
<p>Find me in app/views/likes/count.html.erb</p>

app/views/likes/create.html.erb
<h1>Likes#create</h1>
<p>Find me in app/views/likes/create.html.erb</p>

app/views/likes/delete.html.erb
<h1>Likes#delete</h1>
<p>Find me in app/views/likes/delete.html.erb</p>